name: Send bbangmap dau

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  send_slack_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      env:
          AMPLITUDE_SECRET_KEY: ${{ secrets.AMPLITUDE_SECRET_KEY }}
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
          AMPLITUDE_SLACK_WEBHOOK_URL: ${{ secrets.AMPLITUDE_SLACK_WEBHOOK_URL }}
          BBANGMAP_NOTION_DATABASE_KEY: ${{ secrets.BBANGMAP_NOTION_DATABASE_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      run: |
        python Sources/amplitude_dau.py
        python Sources/notion_working_database.py
